version: '3.9'

services:
  user_db:
    container_name: user_db
    image: postgres:12
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--no-invalidate-on-startup"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}